name: primer workflow
run-name: Workflow para entender el funcionamiento automatizado


on: push

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hola workflow"
      - run: echo "siguiente" > archivo.txt
      - run: sleep 5

  example_job2:   
    runs-on: ubuntu-latest
    steps:
      - run: cat archivo.txt
      - run: echo "hola workflow desde job 2"      
      - run: echo "Final"

 
